Update README.md
dmonjasm/IV pull request #1
Opened 2022-09-20 11:03 UTC by dmonjasm

- [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
- [x] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
- [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
- [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

2022-09-20 11:20 UTC, JJ commented
Ya os comenté el problema que había con llamar al proyecto IV.

2022-09-20 11:21 UTC, dmonjasm commented
¿Lo renombro directamente al nombre del proyecto?

2022-09-20 11:21 UTC, JJ commented
> * [x]   ¿Se trata de un problema real del que se tenga conocimiento personal?
> 

¿Tienes conocimiento personal sobre el envío de formularios y los formatos que requieren?

>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

En el resto de las preguntas, se agradecería una respuesta razonada, aunque sea breve, para que se observe que realmente se ha hecho la diligencia debida.

2022-09-20 11:21 UTC, JJ commented
> ¿Lo renombro directamente al nombre del proyecto?

En el siguiente objetivo, por favor. En este ya está enlazado.

2022-09-20 11:23 UTC, JJ requested changes
La última pregunta la has contestado, pero no las hecho.
Del resto: no es un problema personal ni está claramente identificado, no es algo que no se pueda resolver con un equipo personal porque la conversión de formatos es algo que no requiere acceso a nada online, ni se ha identificado clarametne cuál es la lógica de negocio (y la complicación inherente)

2022-09-20 11:24 UTC, dmonjasm commented
De acuerdo, pienso en otro problema mejor,

2022-09-22 07:55 UTC, dmonjasm commented
* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí, durante 4 años he estado trabajando en Madrid y he tenido que realizar la ruta Madrid-Segovia diariamente. En esta ruta hay un peaje en el cual, en función del periodo y del precio que tenga la gasolina dicho día, sale más rentable evitarlo que cogerlo.

* [x] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
Sería necesario recoger los precios de los distintos peajes repartidos por España, así como los precios que tiene cada uno para los distintos tipos de vehículos y periodos horarios del día.

* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
Sí, va a ser necesario hacer Web Scraping y probar varias combinaciones de rutas, así como hacer una cierta heurística para elegir una ruta teniendo en cuenta su precio y tiempo total.

* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
Sí, todo queda enlazado en el apartado configuración git del README.

2022-09-22 09:22 UTC, JJ commented
Poned la lista de comprobación en el cuerpo, por favor.

2022-09-22 09:23 UTC, JJ approved these changes
👍

2022-09-22 09:30 UTC, dmonjasm commented
Añado en el README la lista de comprobación y hago el merge?

2022-09-22 09:36 UTC, merged