Objetivo 2
dmonjasm/IV pull request #17
Opened 2022-11-10 12:13 UTC by marcosrmartin

Sobre la estructura del repositorio
* [x] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
   disposición de los mismos?
Sobre el análisis del problema
* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.
Sobre la planificación y la programación
* [x] ¿Los issues representan un problema, y no una tarea?
* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están asignados a una HU?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit? Sí Los issues sobre los que estoy trabajando, ¿han
      sido asignados al primer milestone? No, ya que los hemos rehecho.
* [x] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [x] ¿Son los milestones sobre los que estoy trabajando productos
   mínimamente viables? ¿O tengo que solicitar al product manager que
   cree milestones adicionales o precise de qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

Hola Daniel, estas son las estructuras de datos que he pensado que pueden resolver el problema con algunas comprobaciones de errores, si ves que se pueden añadir más lo hablamos.
Aparte de esto, la entidad Ruta he decidido que almacene una puntuación para la heurística, un tramo nuevo y un puntero a otro objeto Ruta, ya que así la estructura se podría usar recursivamente (para algoritmos como Dijkstra, y otros de VRP).
Si ves que hay algo mal dímelo, y le doy otra vuelta, en el caso de ser sobre la ED Ruta, abrimos un issue para discutirlo allí, de lo contrario espero la aprobación.🤝

2022-11-13 10:40 UTC, dmonjasm commented
He estado revisando el código y está todo bien, menos en la implementación de Ruta, que creo que el atributo tramo debería ser una slice o un list ya que entiendo que una ruta tendrá varios tramos y no solo uno. Por otro lado falta añadir la inicialización del modulo (el go.mod) en el directorio raíz. Cambiado eso yo lo veo ya todo bien.

2022-11-13 15:32 UTC, marcosrmartin commented
Lo que he hecho es que una Ruta pueda tener otra Ruta dentro, y como cada Ruta tiene un tramo, ese seria la "list" de tramos, ya que se podría recorrer recursivamente.

2022-11-13 18:15 UTC, dmonjasm commented
vale ya veo lo que dices, pues entonces lo veo todo bien. Le doy el ok

2022-11-13 18:17 UTC, dmonjasm approved these changes
:+1:

2022-11-13 18:19 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-11-13 19:25 UTC, Carlos-SE commented
@marcosrmartin, creo que deberías cambiar los `issues` o crear unos nuevos ya que los que has planteado han sido titulados como si fuesen historias de usuario. También añadir que en los issues no tienes que proponer la solución, tienes que plantear el problema y avanzar sobre ellos con los `commits` adecuados.

2022-11-14 06:52 UTC, JJ commented
> He estado revisando el código y está todo bien, menos en la implementación de Ruta, que creo que el atributo tramo debería ser una slice o un list ya que entiendo que una ruta tendrá varios tramos y no solo uno. Por otro lado falta añadir la inicialización del modulo (el go.mod) en el directorio raíz. Cambiado eso yo lo veo ya todo bien.

Esto debes hacerlo inline en el código correspondiente. Por favor, aprended a hacer estas cosas.

2022-11-14 06:56 UTC, JJ commented
> @marcosrmartin, creo que deberías cambiar los `issues` o crear unos nuevos ya que los que has planteado han sido titulados como si fuesen historias de usuario. También añadir que en los issues no tienes que proponer la solución, tienes que plantear el problema y avanzar sobre ellos con los `commits` adecuados.

Esencialmente es esto mismo. Hay issues que están marcados como historias de usuario pero no lo son, no están relacionados con ninguna historia de usuario, y no plantean problemas. El que (más o menos) plantea uno, el #12 (que tampoco es una historia de usuario) sólo tiene un puñado de commits.

Por favor, seguid también las prácticas habituales en commits "Avanza #xx" no es lo adecuado.

2022-11-14 07:02 UTC, JJ commented
> Sobre la estructura del repositorio
> 
>     * [x]  ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
>       disposición de los mismos?

No estoy seguro de que `internal` sea lo más habitual. He visto `pkg`, por ejemplo, pero no esto.

>       Sobre el análisis del problema
> 
>     * [x]  ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
>       que se ha creado?
> 

Si no lo has hecho, no lo marques.

>     * [x]  ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
>       una entidad o un agregado?
> 

Tampoco.

2022-11-14 07:04 UTC, JJ requested changes
Hay que seguir la metodología propuesta
* Asignar issues a milestones (por parte de @dmonjasm )
* No llamar issues a los que no lo son.
* Issues relacionados siempre con HUs
* Issues que planteen problemas.

Sin una base sólida de issues para trabajar, hay que rehacer gran parte del trabajo, porque el código desarrollado no se ha hecho correctamente.

2022-11-14 07:04 UTC, JJ commented on internal/Posicion.go
> +type Posicion struct{
No parece que esto tenga ninguna relación con la lógica de negocio.

2022-11-14 07:04 UTC, JJ commented on internal/Posicion.go
> +func PosicionError(x float32, y float32) error{
Y esto tampoco.

2022-11-14 07:04 UTC, JJ commented on internal/Tramo.go
> +    inicio Posicion
No creo que se vayan a buscar los tramos por coordenadas geográficas. No pone nada parecido en ninguna HU, ni parece que eso solucione el problema de representar los tramos para usarlos por la lógica de negocio.

2022-11-14 07:04 UTC, JJ commented on internal/Peaje.go
> +    precios map[Peso]float32
Más que peso debería ser tipo de vehículo, no creo que haya solo dos tipos.

2022-11-14 11:18 UTC, dmonjasm commented
> > Sobre la estructura del repositorio
> > ```
> > * [x]  ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
> >   disposición de los mismos?
> > ```
> 
> No estoy seguro de que `internal` sea lo más habitual. He visto `pkg`, por ejemplo, pero no esto.

Buscando las buenas prácticas de GO vi que un proyecto GO básico suele tener tres directorios cmd, pkg e internal. En este caso solo se ha creado internal porque es el directorio que contiene el código privado del proyecto. Adjunto enlace [ProjectStruture](https://dev.to/jinxankit/go-project-structure-and-guidelines-4ccm)

2022-11-14 11:23 UTC, JJ commented
> > > Sobre la estructura del repositorio
> > > ```
> > > * [x]  ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
> > >   disposición de los mismos?
> > > ```
> > 
> > 
> > No estoy seguro de que `internal` sea lo más habitual. He visto `pkg`, por ejemplo, pero no esto.
> 
> Buscando las buenas prácticas de GO vi que un proyecto GO básico suele tener tres directorios cmd, pkg e internal. En este caso solo se ha creado internal porque es el directorio que contiene el código privado del proyecto. Adjunto enlace [ProjectStruture](https://dev.to/jinxankit/go-project-structure-and-guidelines-4ccm)

¿Por qué es privado y no externo? ¿Cómo has modelado el código para decidir eso?

2022-11-14 11:34 UTC, dmonjasm commented
> > > > Sobre la estructura del repositorio
> > > > ```
> > > > * [x]  ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
> > > >   disposición de los mismos?
> > > > ```
> > > 
> > > 
> > > No estoy seguro de que `internal` sea lo más habitual. He visto `pkg`, por ejemplo, pero no esto.
> > 
> > 
> > Buscando las buenas prácticas de GO vi que un proyecto GO básico suele tener tres directorios cmd, pkg e internal. En este caso solo se ha creado internal porque es el directorio que contiene el código privado del proyecto. Adjunto enlace [ProjectStruture](https://dev.to/jinxankit/go-project-structure-and-guidelines-4ccm)
> 
> ¿Por qué es privado y no externo? ¿Cómo has modelado el código para decidir eso?

Entiendo que el modelado de las entidades y objetos valor de este proyecto son útiles sólo para este proyecto, luego por eso se mete en internal. Tenía entendido que en pkg se mete aquel código que puede ser útil para otro proyecto o servicios.

2022-11-22 10:05 UTC, Carlos-SE commented
Buenas, @marcosrmartin. Los issues ya tienen mejor pinta, sigue así y mucho ánimo! 👍

2022-11-22 16:20 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-11-22 16:32 UTC, JJ requested changes
Los issues no plantean realmente ningún problema, y no se ha hecho ningún intento por modelizar el mismo. Por ejemplo, no se da ninguna pista sobre como se va a llevar a cabo #3 o como esto contribuye a eso.

2022-11-22 16:32 UTC, JJ commented on internal/ruta.go
> +	precio float32
¿Precio o coste?

2022-11-22 16:32 UTC, JJ commented on internal/ruta.go
> +	return &Ruta{0, tramos}, nil
No sé si el PMV incluye inicializar el coste, pero si lo hace, ¿por qué es cero siempre?
Si modelizar tramos de autopistano es de este PMV, ¿por qué lo pones?

2022-11-22 18:23 UTC, marcosrmartin commented on internal/ruta.go
> +	return &Ruta{0, tramos}, nil
No lo tiene que inicializar, pero en go los enteros no se pueden inicializar a nulo, su equivalente es 0, o se podría utilizar un valor negativo. En cuanto a los tramos los propongo porque no puedes calcular una ruta sin saber de que está compuesta.

2022-11-22 18:43 UTC, JJ commented on internal/ruta.go
> +	return &Ruta{0, tramos}, nil
¿Y por qué no lo pasa al constructor entonces?
En todo caso, ¿por qué no se ha planteado eso en un issue?

2022-11-22 19:18 UTC, marcosrmartin commented on internal/ruta.go
> +	return &Ruta{0, tramos}, nil
Miento, el coste se debería de calcular con otra función, pero esta debería de estar incluida en el constructor, aunque llevaría a cabo la lógica de negocio, pero como no es está incluido en este PMV lo inicializo a ""nulo"". En cuanto a porque no se ha planteado tramos como un issue, es porque lo entiendo como una solución al problema de representar una Ruta, y en los issues no se deben proponer soluciones, realmente uso tramo porque en Go no existen tuplas y uso esa clase como apoyo para Ruta.

2022-12-01 18:06 UTC, marcosrmartin commented
@JJ Listo para revisión.

2022-12-02 11:25 UTC, JJ approved these changes
No has justificado mucho cómo has hecho el modelo, pero lo hemos hablado en clase, así que por mi :+1:

2022-12-02 15:23 UTC, merged