[IV 22-23] Objetivo 3
dmonjasm/IV pull request #26
Opened 2022-12-01 19:22 UTC by dmonjasm

* [x] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x] ¿Ese issue está asignado a un milestone?
* [x] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [x] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [x] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [x] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2022-12-02 09:00 UTC, dmonjasm commented
@JJ solicito revisión.

2022-12-08 14:16 UTC, dmonjasm commented
@JJ Listo para revisión.

2022-12-09 08:35 UTC, JJ requested changes
Tienes bastantes ficheros que no deben estar. Por otro lado, no has hecho ninguna justificación de las herramientas elegidas como se pide en el objetivo (de hecho, *es* el objetivo)

2022-12-09 09:10 UTC, dmonjasm commented
> Tienes bastantes ficheros que no deben estar. Por otro lado, no has hecho ninguna justificación de las herramientas elegidas como se pide en el objetivo (de hecho, _es_ el objetivo)

¿Las elecciones de #23 y #24 no valen?

2022-12-09 09:13 UTC, JJ commented
> > Tienes bastantes ficheros que no deben estar. Por otro lado, no has hecho ninguna justificación de las herramientas elegidas como se pide en el objetivo (de hecho, _es_ el objetivo)
> 
> ¿Las elecciones de #23 y #24 no valen?

Evalúo lo que está en el PR; es la mejor forma de comentarlo porque se puede hacer por líneas. Por favor, tratad de hacer las cosas lo más fáciles posibles para la persona que revisa.

2022-12-09 09:18 UTC, dmonjasm commented
De acuerdo, entonces creo que la justificación la incluiré en el README

2022-12-09 11:37 UTC, dmonjasm commented
Listo para revisión @JJ

2022-12-09 19:05 UTC, JJ requested changes
Aclara un poco, por favor, lo que has elegido y por qué.

2022-12-09 19:05 UTC, JJ commented on README.md
> ++ Deuda técnia. Soporte. Documentación.
Los dos segundos no son muy objetivos.

2022-12-09 19:05 UTC, JJ commented on README.md
> +He decidido utilizar el *task runner* implícito de GO. Se trata del estándar que recomienda GO y además tiene un amplio soporte, mientras que Task solo cumple el criterio de deuda técnica.
No estás usando este, sino `make`. Justifica lo que estés usando en realidad. No sé si "el runner que lleva go" es capaz de hacer lo que `make` y todo tipo de tareas más allá de las implícitas, lo dudo mucho.

2022-12-09 19:05 UTC, JJ commented on README.md
> +Por otro lado, en los requisitos del objetivo 3 nos pide que incluyamos una clave fichero en el iv.yaml que apuntará al archivo que se usará para ejecutar las tareas. Debido a esto he decido combinar
No estás combinando, esás eligiendo `make`.

2022-12-09 19:05 UTC, JJ commented on README.md
> +Creo que a pesar de combinar con Make sigue siendo mejor opción, ya que buscando comparaciones entre Make y Task, no he encontrado una clara ventaja para elegir uno sobre otro. Luego la deuda técnica
Tendrás que aclarar un poco lo de la deuda técnica...

2022-12-09 19:05 UTC, JJ commented on internal/ruta.go
> +package internal
¿Por qué incluís cosas que no corresponden a este objetivo?

2022-12-09 20:53 UTC, dmonjasm commented on internal/ruta.go
> +package internal
Este código procede del merge del Objetivo 2.

2022-12-10 08:31 UTC, JJ commented on internal/ruta.go
> +package internal
La pregunta es la misma. Este PR es para evaluar este objetivo. Os agradecería que incluyérais solo lo evaluable.

2022-12-10 17:02 UTC, dmonjasm commented on internal/ruta.go
> +package internal
De acuerdo, elimino internal/tramo.go. internal/ruta.go lo tengo que dejar, pues lo pide el iv.yaml como y tengo que comprobar su sintaxis como parte del objetivo 3. La primera línea que me ha marcado es necesaria para la comprobación de la sintaxis.

2022-12-10 17:03 UTC, dmonjasm commented on internal/ruta.go
> +package internal
¿Lo que no compete ha este objetivo es la línea marcada?

2022-12-10 17:34 UTC, JJ commented on internal/ruta.go
> +package internal
Lo que no está relacionado es lo que no aparece en el guión, en general.

2022-12-10 19:47 UTC, dmonjasm commented on internal/ruta.go
> +package internal
Pero el objetivo pide la comprobación de la sintaxis entidad y para eso necesito el código de internal, incluido el package internal. Si quito cualquiera de los archivos de código o el package internal me da error, pues espera un paquete al comienzo del archivo.

2022-12-11 09:12 UTC, JJ commented on internal/ruta.go
> +package internal
Sólo necesitas el fichero, es lo que comprueba. Y sólo un fichero.

2022-12-11 11:54 UTC, dmonjasm commented
Listo para revisión @JJ

2022-12-11 12:47 UTC, JJ requested changes
Por favor, mira los errores frecuentes en este objetivo. Especialmente, los criterios tienen que ser objetivos.

2022-12-11 12:47 UTC, JJ commented on README.md
> ++ El *task runner* implícito de GO se trata de una herramienta para la gestión de código GO.
No existe ningún task runner en go. Existe la herramienta de línea de órdenes, que ejecuta comandos predeterminados. Tú no puedes añadir nuevos comandos, que es lo que permite un task runner.

2022-12-11 12:47 UTC, JJ commented on README.md
> +    + Make sigue recibiendo soporte, en concreto la última actualización es del 31 de Octubre de 2022, luego cumple el requisito del mantenimiento. Además a diferencia de Task, debido a la gran popul
Por favor, ahorraros detalles irrelevantes. Decid cómo cumple vuestros criterios y en qué medida.

2022-12-11 12:47 UTC, JJ commented on README.md
> ++ Estándares de GO.
¿Qué estándares hay en ejecutar tareas?

2022-12-11 12:47 UTC, JJ commented on README.md
> ++ Funcionalidades.
¿Cómo se mide esto objetivamente?

2022-12-11 17:11 UTC, JJ requested changes
Se trata en este objetivo de que aprendáis una forma precisa de elegir dependencias sin introducir deuda técnica y de forma que la justificación sea válida. Por favor, trata de hacerlo así. Consulta los errores comunes de este objetivo en las sesiones anteriores a esta.

2022-12-11 17:11 UTC, JJ commented on README.md
> ++ Funcionalidades.
:arrow_double_up:

2022-12-11 17:11 UTC, JJ commented on README.md
> ++ Instalación. Si la requiere, y en caso de así ser, cómo de compleja es la misma.
¿Cómo mides la complejidad de la instalación?

2022-12-11 17:11 UTC, JJ commented on README.md
> +    + Requiere la instalación de código así como añadir el mismo a las variables de entorno del sistema.
¿Qué es "instalación de código"? Es un binario, ¿no? Habrá que añadirlo al path, exactamente igual que make

2022-12-11 17:11 UTC, JJ commented on README.md
> +    + Task incluye funcionalides que permiten modificar la forma de ejecutar las tareas, el directorio de ejecución, el formato de la salida, entre otras muchas posibilidades.
"Funcionalidades" sigue sin ser una medida objetiva. O pones las funcionalidades que quieres como requisitos (y las justificas) o no las pongas. Si no lo haces así, es simplemente una forma de decir "elijo este porque tiene estas funcionalidades" para que "salga" el que quieres.

2022-12-11 17:11 UTC, JJ commented on README.md
> ++ La última opción considerada es [Make](https://www.gnu.org/software/make/). También requiere la instalación de código externo, aunque suele venir como parte de muchas distribuciones Linux.
De veras, no veo qué problema es instalar cosas. Cualquiera va a necesitar que se instale algo, ¿no?

2022-12-11 17:11 UTC, JJ commented on README.md
> +    + Make incluye funcionalidades que permiten modificar sobre que archiovs se ejecutan las tareas, la forma en que se ejecutan, el formato de salida, el archivo que se va a usar como Makefile (por
typo, pero se aplica lo que he dicho arriba de las funcionalidades.

2022-12-11 17:11 UTC, JJ commented on README.md
> +Task y Make son dos buenos candidatos para usar como gestor de tareas, pero he decidido utilizar Make. Buscando comparaciones entre Make y Task, no he encontrado una clara ventaja para elegir uno sob
O sea, que no has usado ninguno de los criterios objetivos que has puesto arriba. Y por favor, corrige los errores de tecleo.
Y de veras, esa frase ni siquiera tiene sentido:

> inlcuye algunas más que nos permiten tener en cuenta la ocupación actual, como por ejemplo -l

Es una frase mal traducida de algún otro artículo. Os rogaría que no hiciérais esto

2022-12-11 17:11 UTC, JJ commented on README.md
> +En los requisitos del objetivo 3 nos pide que incluyamos una clave fichero en el iv.yaml que apuntará al archivo que se usará para ejecutar las tareas. En este caso el fichero va a ser el Makefile
Si lo pide y lo habéis hecho, y se comprueba automáticamente, ¿por qué lo pones?

2022-12-12 16:14 UTC, dmonjasm commented
Listo para revisión @JJ

2022-12-12 16:17 UTC, JJ approved these changes
:+1:

2022-12-12 16:17 UTC, JJ commented on README.md
> +    + Task es más rápido en la ejecución de tareas que Make, para ello se han ejecutado tareas de compilación e instalación de dependencias y se han demostrado que los tiempos obtenidos por Task han
Esto quedaría mucho mejor si pusieras el tiempo que se tarda.

2022-12-12 16:18 UTC, dmonjasm commented on README.md
> +    + Task es más rápido en la ejecución de tareas que Make, para ello se han ejecutado tareas de compilación e instalación de dependencias y se han demostrado que los tiempos obtenidos por Task han
De acuerdo lo incluyo antes de cerrar el PR

2022-12-12 17:12 UTC, merged