[IV 22-23] Objetivo 1
dmonjasm/IV pull request #6
Opened 2022-09-29 14:42 UTC by dmonjasm

2022-09-29 14:58 UTC, dmonjasm commented
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
Sí, las historias de usuario y los milestones dan una guía suficiente de cual es el camino que se quiere seguir para este servicio.

* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
Sí, se han ido construyendo los milestones de forma que sigan un orden y que mantengan un orden lógico.

* [x]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
Sí, se han pensado de forma que cada uno  aporte una pequeña funcionalidad para progresar en el proyecto.

* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
Sí, se ha mencionado en un documento aparte las historias de usuario con la frecuencia, el contexto, el dispositivo y los pasos a seguir por los usuarios.

* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?
Sí, todas las historias de usuario representan casos relacionados con la lógica de negocio y son acciones que los usuarios realizarían por su beneficio propio.

Listo para revisión.

2022-09-29 18:28 UTC, JJ requested changes
Por favor, revisa los conceptos de HU pero, sobre todo, de PMV según lo indicado.

2022-09-29 18:28 UTC, JJ commented on docs/historias_usuario.md
> +la ruta más adecuada. Debe introducir la información del vehículo, el precio de la gasolina del sitio más caro donde vaya a recargar y el origen y destino deseados.
Una HU no tiene detalles de implementación.

2022-09-29 18:28 UTC, JJ commented on docs/historias_usuario.md
> +la ruta más adecuada. Debe introducir la información del vehículo, el precio de la gasolina del sitio más caro donde vaya a recargar y el origen y destino deseados.
Y *nunca* tienes que pedirle que introduzca ese tipo de cosas. Ese es el valor que debe proporcionar la aplicación.

2022-09-29 18:28 UTC, JJ commented on docs/historias_usuario.md
> +del vehículo, el precio de la gasolina del sitio donde suela recargar y el origen y destino deseados.
Lo ideal es que no metiera nada. Lo segundo ideal, que todo lo que se pueda extraer automáticamente, lo haga. ¿Yo os digo que tecleéis el número de milestones o lo pido al API de GitHub?

2022-09-29 18:28 UTC, JJ commented on docs/historias_usuario.md
> +[[HU3]](https://github.com/dmonjasm/RouteCheck/issues/4) [Juan Manuel](https://github.com/dmonjasm/RouteCheck/blob/Objetivo-1/docs/personas.md#juan-manuel-g%C3%B3mez-mart%C3%ADn) utiliza el servicio
No veo que estas HUs usen diferentes lógicas de negocio. Si no lo hacen, no las incluyas.

2022-09-29 18:28 UTC, JJ commented on docs/milestones.md
> +- [M3] [Estructura de datos para representar las rutas](https://github.com/dmonjasm/RouteCheck/milestone/4)
Agrupa los milestones que sean funcionalmente similares. Es una unidad de trabajo que debería durar un sprint, no puedes poner una estructura de datos.

2022-09-29 18:28 UTC, JJ commented on docs/milestones.md
> +- [M4] [Estructura de datos para representar los peajes](https://github.com/dmonjasm/RouteCheck/milestone/5)
¿Los peajes necesitan una estructura de datos específica? ¿Seguro? ¿No será mejor que pongas en un solo milestones todas las estructruas de datos _necesarias_ sin decidir de antemano cómo modelizar el problema?

2022-09-29 18:28 UTC, JJ commented on docs/milestones.md
> +- [M5] [Librería para recoger los datos del peaje de fuentes externas](https://github.com/dmonjasm/RouteCheck/milestone/6)
No necesitas los datos para aplicar la lógica de negocio. Necesitas el formato de los datos, esencialmente.

2022-09-29 18:28 UTC, JJ commented on docs/milestones.md
> +- [M6] [Función/Método que genere los datos de duración y precio de las distintas rutas](https://github.com/dmonjasm/RouteCheck/milestone/7)
Si no puedes decidir la viabilidad de esto independientemente, no puede ser un PMV.

2022-09-29 19:14 UTC, dmonjasm commented on docs/milestones.md
> +- [M5] [Librería para recoger los datos del peaje de fuentes externas](https://github.com/dmonjasm/RouteCheck/milestone/6)
No acabo de entender lo del formato de los datos. Pensaba que necesitaba extraer la información de los pdf que se encuentran en la página del ministerio de transporte.

2022-09-30 05:41 UTC, JJ commented on docs/milestones.md
> +- [M5] [Librería para recoger los datos del peaje de fuentes externas](https://github.com/dmonjasm/RouteCheck/milestone/6)
No, necesitas qué tipo de información hay para modelizar el problema. Sólo necesitas los datos reales para testar y producción.

2022-09-30 05:44 UTC, JJ requested changes
Tienes que reordenar los datos de forma que la lógica de negocio se lleve a cabo lo antes posible. No necesitas los datos, sino formato, rango de variación y sólo lo necesario para testear.

2022-09-30 05:44 UTC, JJ commented on docs/milestones.md
> +  - Vehículo
Siguen siendo detalles de implementación que tienes que decidir en el proceso de desarrollo. No lo anticipes en un milestone.

2022-09-30 05:44 UTC, JJ commented on docs/milestones.md
> +- [M3] [Función que calcule una estimación del precio para la ruta.](https://github.com/dmonjasm/RouteCheck/milestone/10)
Por favor, reordena estos milestones para que la lógica de negocio esté en un punto más avanzado. No puedes hacer nada con los datos si no tienes lógica de negocio. Para testear esta no hace falta más que datos simulados.

2022-09-30 09:04 UTC, dmonjasm commented
De acuerdo, voy a darle una vuelta a los milestones antes de la siguiente revisión. El tema de las historias de usuario si queda ya arreglado?

2022-09-30 12:30 UTC, JJ commented
> De acuerdo, voy a darle una vuelta a los milestones antes de la siguiente revisión. El tema de las historias de usuario si queda ya arreglado?

Si no he dicho nada...

2022-10-06 07:20 UTC, dmonjasm commented
"Listo para revisión"

2022-10-06 07:34 UTC, dmonjasm commented
Listo para revisión

2022-10-06 07:37 UTC, JJ approved these changes
👍

2022-10-06 07:40 UTC, merged